# Generated by Django 4.0.3 on 2022-03-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('no', models.CharField(max_length=10, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=100)),
            ],
        ),
    ]
